# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 12:57
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='hash',
        ),
        migrations.AddField(
            model_name='name',
            name='hash_1',
            field=models.CharField(default=api.models._createHash, max_length=10, unique=True),
        ),
    ]
