# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 14:33
from __future__ import unicode_literals

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170316_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='hash_1',
            field=models.CharField(default=api.models._createHash, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
